server:
  port: 8888

spring:
  # thymeleaf 模板配置
  thymeleaf:
    check-template-location: true
    suffix: .html
    mode: HTML
    encoding: UTF-8
    prefix: classpath:templates/
    cache: true
open-url: http://127.0.0.1:${server.port}
app-code: 阿里云服务的app code
wei-xin-url: 企业微信机器人